<a href="https://colab.research.google.com/github/DSWoodin/Pythonworkspace/blob/main/ProDS/EDA_%EC%88%98%EC%B9%98%ED%98%95%EB%B2%94%EC%A3%BC%ED%98%95%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [9]:
np.array([1,2,3,4]).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [10]:
array = np.array([[1,2,3], [4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array[0]

array([1, 2, 3])

In [12]:
array[1]

array([4, 5, 6])

In [13]:
array[1][1]

5

In [15]:
array[1,1] # array[row index, col index] == array[row index][col index]

5

In [18]:
array.ndim # ndim -> number of dimension

2

In [19]:
array.shape

(2, 3)

In [20]:
array.sum()

21

In [21]:
array.std()

1.707825127659933

In [22]:
nums = np.array([1,2,2,3])
nums

array([1, 2, 2, 3])

In [23]:
set(nums) # set -> 집합형 변수(중복 미허용)

{1, 2, 3}

In [24]:
len(nums)

4

In [25]:
np.unique(nums)

array([1, 2, 3])

In [26]:
len(np.unique(nums))

3

In [27]:
np.arange(start=5, stop=20, step=5)

array([ 5, 10, 15])

In [28]:
nums

array([1, 2, 2, 3])

In [30]:
np.where(nums==2, 'ok!', 'no!') # 조건이 True인 행과 False인 행에 각각 대치

array(['no!', 'ok!', 'ok!', 'no!'], dtype='<U3')

In [31]:
import pandas as pd

In [32]:
ser = pd.Series([1,2,3])
ser

0    1
1    2
2    3
dtype: int64

In [33]:
ser.values

array([1, 2, 3])

In [35]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [36]:
ser2 = pd.Series([1,2,3], index=['a','b','c'])
ser2

a    1
b    2
c    3
dtype: int64

In [37]:
ser3 = pd.Series([2,4,4,6,7,8])
ser3

0    2
1    4
2    4
3    6
4    7
5    8
dtype: int64

In [38]:
ser3.idxmax()

5

In [39]:
ser3.idxmin()

0

In [40]:
ser3.isin([6,7])

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [41]:
True + True

2

In [42]:
True + False

1

In [43]:
False + False

0

In [44]:
ser3.isin([6,7]).sum()

2

In [45]:
ser4 = pd.Series([1,2,3,3,4])
ser4[0]

1

In [47]:
ser4[[1,3]]

1    2
3    3
dtype: int64

In [48]:
ser4[2:]

2    3
3    3
4    4
dtype: int64

In [49]:
ser4[:3]

0    1
1    2
2    3
dtype: int64

In [50]:
ser4[:-1]

0    1
1    2
2    3
3    3
dtype: int64

In [52]:
df = pd.DataFrame({'aa':[1,2,3],
                   'bb':[4,5,6]})
df

aa  bb
0   1   4
1   2   5
2   3   6

In [53]:
df['aa']

0    1
1    2
2    3
Name: aa, dtype: int64

In [54]:
df['aa'][0]

1

In [55]:
df.iloc[1,1] # iloc: 정수 기반 인덱싱

5

In [56]:
df.iloc[:,0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [57]:
df.loc[0,'aa'] # loc: 레이블 기반 인덱싱

1

In [58]:
pd.crosstab(df['aa'], df['bb']) # 빈도표

bb  4  5  6
aa         
1   1  0  0
2   0  1  0
3   0  0  1

In [59]:
df.groupby('aa')['bb'].sum()

aa
1    4
2    5
3    6
Name: bb, dtype: int64