<a href="https://colab.research.google.com/github/DSWoodin/Practice/blob/main/PKNU_5th/01_DA/01_PythonBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 강의 분량
* 07월05일(금) 8시간
* 07월06일(월) 1시간

### 강의 자료
* 파이썬기초

### 이 장에서 배우는 것
* 변수 할당
* 문자열
* len()
* type()
* 자료형 변환
* input()
* 산술 연산
* 비교 연산
* 논리 연산
* random 모듈
* if:
* for:
* while:
* continue
* def:
* 리스트와 append()
* 슬라이싱
* remove(), pop()
* index()
* sort(), sorted(), 파라미터 reverse
* 리스트 함축(list comprehension)
* 튜플
* 딕셔너리
* lambda
* numpy 라이브러리
* np.array()
* shape, ndim, dtype
* 넘파이 인덱싱, 슬라이싱, 불리언 인덱싱
* 2차원 배열, 인덱싱, 슬라이싱
* np.arange()
* np.linspace()
* np.reshape()
* np.flatten()

## 변수 할당

In [ ]:
# 주석문 (comments)
# 파이썬 변수(variable) 정의
weight=78.2

In [ ]:
weight

78.2

In [ ]:
weight=76.9
weight

76.9

In [ ]:
x=100
y=200
x,y

(100, 200)

In [ ]:
print(x,y)

100 200


In [ ]:
# 동시 할당문
a,b=50,20
result=a*b
result

1000

In [ ]:
# 특수문자 : *, / & 는 변수이름으로 _ 를 제외하고는 사용하지 않는다.
_b=100
# 예약어(keyword) : for, if, return 는 당연히 변수명으로 사용해서는 안된다.


## 문자열

In [ ]:
# 문자열 (string)
s1='Hello World'
s1

'Hello World'

In [ ]:
s1="Hello World"
s1

'Hello World'

In [ ]:
message = "철수가 "안녕"이라고 말했습니다."
message

SyntaxError: invalid syntax (<ipython-input-21-18c2ea4e8a50>, line 1)

In [ ]:
message = '철수가 "안녕"이라고 말했습니다.'
message

'철수가 "안녕"이라고 말했습니다.'

## len()

In [ ]:
# 변수 정의, 값(숫자형, 문자열) 할당, 함수
# 함수에서는 input의 형태, return 값의 형태
a1=len(message)
a1

18

In [ ]:
s1="Hello"
s2="World"
s1+s2

'HelloWorld'

In [ ]:
n1=100
n2=200
n1+n2

300

In [ ]:
n1='100'
n2='200'
n1+n2

'100200'

In [ ]:
n1='100'
n2=200
n1+n2

TypeError: can only concatenate str (not "int") to str

## type()

In [ ]:
# 자료의 형태 : int, float, str, bool
# int : 정수형, -3, -2, -1, 0, 1, 2, 3 (어떤 범위안 정수의 개수 유한)
# float : 실수형, 3.14, 4.28, ... (어떤 범위안 실수의 개수 무한 : 1=>0.999999999999999999999)
# str : 문자열 'Hellow world', "100"
# bool : True(=1), False(=0), 조건연산시

In [ ]:
weight=78.2
type(weight)

float

In [ ]:
salary=250
type(salary)

int

In [ ]:
name='홍길동'
type(name)

str

In [ ]:
bool1=True
type(bool1)

bool

## 산술연산

In [ ]:
# 자료형태에 따른 연산
x=10
y=20
x+y

30

In [ ]:
x='good'
y='morning'
x+y

'goodmorning'

In [ ]:
'23'+'10'

'2310'

In [ ]:
23+10

33

In [ ]:
100+'원'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## 자료형 변환

In [ ]:
# 자료형 변환
# str(), int(), float()

In [ ]:
print(str(100)+'원')
print(str(100))

100원
100


In [ ]:
str(3.14)

'3.14'

In [ ]:
int("100")

100

In [ ]:
float("100")

100.0

In [ ]:
print(int(100.0))
print(float(100))

100
100.0


## input()

In [ ]:
# input 함수
x=int(input("첫번째 숫자를 입력하세요."))
y=int(input("두번째 숫자를 입력하세요."))
s=x+y
print(x, "과", y, "의 합은", s, "입니다.")

첫번째 숫자를 입력하세요.100
두번째 숫자를 입력하세요.200
100 과 200 의 합은 300 입니다.


In [ ]:
# input 함수
x=input("첫번째 숫자를 입력하세요.")
y=input("두번째 숫자를 입력하세요.")
s=x+y
print(x, "과", y, "의 합은", s, "입니다.")

첫번째 숫자를 입력하세요.100
두번째 숫자를 입력하세요.200
100 과 200 의 합은 100200 입니다.


In [ ]:
# 할당(assignment)
x=10
y=20
z=x+y
print(z)

30


In [ ]:
10+20=z # 오른쪽으로 assignment error

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (<ipython-input-59-9ff3e59df83a>, line 1)

In [ ]:
# 다중 할당
x = y =200 # (1) y=200, (2) x=y
print(x,y)

200 200


In [ ]:
n1,n2=100,200 # (1) n1=100 (2) n2=200
print(n1,n2)

100 200


In [ ]:
# 산술연산자(arithmetic operator)
print(7+4)
print(7-4)
print(7*4)
print(7/4)

11
3
28
1.75


In [ ]:
print(7**4) # 지수

2401


In [ ]:
print(7//4) # 몫
print(7%4) # 나머지

1
3


In [ ]:
2**7

128

In [ ]:
2*(3**2) #연산자 운선순위가 혼동 ==> () 연산자를 적극 활용

18

In [ ]:
2+3*2

8

In [ ]:
(2*3)**2

36

In [ ]:
num=200
num+=100 # num=num+100
print(num)

300


In [ ]:
num=200
num-=100 # num=num-100
print(num)

100


## 비교 연산

In [ ]:
a, b = 100, 200

In [ ]:
a==b

False

In [ ]:
a!=b

True

In [ ]:
a >= b

False

In [ ]:
a > = b

SyntaxError: invalid syntax (<ipython-input-78-81fa1d79b65f>, line 1)

## 논리 연산

In [ ]:
# 논리연산자 (logical operator) : and, or, not
x,y = True, False
print(x and y)
print(x or y)
print(not x)

False
True
False


## random 모듈

In [ ]:
# random 모듈 : 난수 생성
import random

In [ ]:
random.random() # 0~1 사이에 임의의 실수값을 return

0.4289060237047889

In [ ]:
random.randint(1,3)

2

In [ ]:
random.randrange(7) # 0~6 까지의 임의의 정수를 return

5

In [ ]:
lst=[10,20,30,40,50]
random.choice(lst)

20

In [ ]:
random.sample(lst, 4)

[40, 50, 30, 10]

In [ ]:
random.choices(lst,k=4)

[20, 40, 20, 20]

## if:

In [ ]:
# if 조건문
score = int(input("점수를 입력하시오."))
if (score >=90):
  print("축하합니다.")
  print("A학점입니다.")
  print("AAA")

점수를 입력하시오.95
축하합니다.
A학점입니다.
AAA


In [ ]:
# if-elif-else
num=int(input("정수를 입력하시오: "))
if num>0:
  print("양수입니다.")
elif num==0:
  print("0입니다.")
else:
  print("음수입니다.")

정수를 입력하시오: -5
음수입니다.


In [ ]:
# if 문 : 논리 연산자와 활용
num = int(input("양의 정수를 입력하시오: "))
if (num %2 == 0) and (num<10):
  print('짝수이고 10보다 작습니다.')
elif (num %2 == 0):
  print('짝수이면서 10보다 크거나 같습니다.')
else:
  print('홀수입니다.')

양의 정수를 입력하시오: 4
짝수이고 10보다 작습니다.


## for:

In [ ]:
# 반복문
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in [100,200,1,1000]: # 리스트 [,,]
  print(i)

100
200
1
1000


In [ ]:
for i in "Hello":
  print(i)

H
e
l
l
o


In [ ]:
for i in range(1,6,2):
  print(i)

1
3
5


## while:

In [ ]:
# while 문
count =1
s =0
while count <= 10:
  s+=count #s = s+count
  count+=1
print(s)
print(count)

55
11


## continue

In [ ]:
# continue
st = "I love Python Programming"
for ch in st:
  if ch in ['a','e','i','o','u','A','E','I','O','U']:
    continue
  print(ch,end='')

 lv Pythn Prgrmmng

## def:

In [ ]:
# 함수
def calculate_area(radius):
  area=3.14*(radius**2)
  return area

In [ ]:
calculate_area(5.0)+calculate_area(2.0)

91.06

In [ ]:
def get_sum(start,end):
  s=0
  for i in range(start,end+1):
    s+=i
  return s

In [ ]:
get_sum(1,100)

5050

## list

In [ ]:
# 리스트 (list) : 값들의 묶음, [] 저장, 어떤 type 이든 가능
heights=[178.9, 173.5, 166.1, 164.3, 176.4]
print(type(heights))
print(len(heights))
heights[4]

<class 'list'>
5


176.4

In [ ]:
bts=['V','Jungkook','Jimin']
bts

['V', 'Jungkook', 'Jimin']

## append()

In [ ]:
# null list 정의후 append 메소드 함수
bts=[]
bts.append('V')
print(bts)
bts.append('Jungkook')
print(bts)

['V']
['V', 'Jungkook']


In [ ]:
bts=bts+['Suga','Jin']
bts

['V', 'Jungkook', 'Suga', 'Jin']

In [ ]:
# range 를 리스트화
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(1,5,2))

[1, 3]

In [ ]:
list(range(2,5))

[2, 3, 4]

In [ ]:
[10,20,30] + [40,10,50]

[10, 20, 30, 40, 10, 50]

In [ ]:
print(bts)

['V', 'Jungkook', 'Suga', 'Jin']


In [ ]:
'V' in bts # in 연산

True

In [ ]:
'V' not in bts # not in 연

False

In [ ]:
# 리스트는 여러 타입을 섞는 것이 가능
slist1=['Kim',123,'Lee',55]
slist1

['Kim', 123, 'Lee', 55]

In [ ]:
slist2=[['Kim',123],['Lee',55]]
slist2

[['Kim', 123], ['Lee', 55]]

In [ ]:
print(slist2[0])

['Kim', 123]


In [ ]:
print(slist2[1])

['Lee', 55]


In [ ]:
n_list=[200,700,500,300,400]
print(len(n_list))
print(max(n_list))
print(min(n_list))
print(sum(n_list))

5
700
200
2100


## 슬라이싱

In [ ]:
#슬라이싱
letters=['A','B','C','D','E','F']
letters[len(letters)-1]

'F'

In [ ]:
letters[-1]

'F'

In [ ]:
letters[2:5]

['C', 'D', 'E']

In [ ]:
letters[3:]

['D', 'E', 'F']

In [ ]:
letters[::2]

['A', 'C', 'E']

In [ ]:
letters[::-1]

['F', 'E', 'D', 'C', 'B', 'A']

## remove(), pop()

In [ ]:
bts

['V', 'Jungkook', 'Suga', 'Jin']

In [ ]:
if 'V' in bts:
  bts.remove("V")
print(bts)

['Jungkook', 'Suga', 'Jin']


In [ ]:
bts.pop()

'Jin'

In [ ]:
bts

['Jungkook', 'Suga']

## index()

In [ ]:
bts.index('Suga')

1

In [ ]:
bts[bts.index('Suga')]

'Suga'

In [ ]:
for i in bts:
  print(i)

Jungkook
Suga


In [ ]:
bts.append(['AA','AAA'])
bts

['Jungkook', 'Suga', ['AA', 'AAA'], ['AA', 'AAA']]

## sort()

In [ ]:
numbers=[9,6,7,1,8,4,5]
numbers.sort() # ascending 오름차순
numbers

[1, 4, 5, 6, 7, 8, 9]

In [ ]:
numbers.sort(reverse=True) #descending 내림차순
numbers

[9, 8, 7, 6, 5, 4, 1]

In [ ]:
numbers=[9,6,7,1,8,4,5]
numbers1=sorted(numbers)
numbers2=sorted(numbers,reverse=True)
print(numbers1)
print(numbers2)

[1, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 1]


## 리스트 함축(list comprehension)

In [ ]:
# 리스트 함축
a1=[1,2,3,4,5]

In [ ]:
a2=[]
for i in a1:
  a2.append(i**2)
print(a2)

[1, 4, 9, 16, 25]


In [ ]:
a3=[i**2 for i in a1]
print(a3)

[1, 4, 9, 16, 25]


In [ ]:
st="Hello World"
st1=[i.upper() for i in st]
print(st1)

['H', 'E', 'L', 'L', 'O', ' ', 'W', 'O', 'R', 'L', 'D']


In [ ]:
''.join(st1)

'HELLO WORLD'

In [ ]:
res=[]
for i in range(1,11):
  a1=i**2
  if (i % 2 ==0 ):
    res.append(a1)
print(res)

[4, 16, 36, 64, 100]


In [ ]:
res1=[i**2 for i in range(1,11) if i%2 ==0]
res1

[4, 16, 36, 64, 100]

## 튜플

In [ ]:
# 튜플(tuple) : 값을 고칠 수 없는 자료 묶
t1=(10,20,30)
l1=[10,20,30]
l1[0]=100
print(l1)

[100, 20, 30]


In [ ]:
t1[0]

10

In [ ]:
t1[0]=100

TypeError: 'tuple' object does not support item assignment

## 딕셔너리

In [ ]:
# 딕셔너리 (dict) : value와 관련된 key 가 있는 데이터 type
phone_book={} # null dict
phone_book['홍길동']='010-1234-5678'
phone_book['김철수']='010-9876-5432'
phone_book

{'홍길동': '010-1234-5678', '김철수': '010-9876-5432'}

In [ ]:
phone_book['홍길동']

'010-1234-5678'

In [ ]:
phone_book.keys()

dict_keys(['홍길동', '김철수'])

In [ ]:
phone_book.values()

dict_values(['010-1234-5678', '010-9876-5432'])

In [ ]:
phone_book.items()

dict_items([('홍길동', '010-1234-5678'), ('김철수', '010-9876-5432')])

## lambda

In [ ]:
# 람다함수 : 익명함수
print('100과 200의 합 : ',(lambda x,y: x+y)(100,200))

100과 200의 합 :  300


In [ ]:
t=(100,200,300)
(lambda x: x[0])(t)

100

In [ ]:
(lambda x: x[1])(t)

200

## numpy

In [ ]:
import numpy as np

In [ ]:
mid_scores=np.array([10,20,30])
final_scores=np.array([60,70,80])

In [ ]:
total=(mid_scores+final_scores)/2
print(total)

[35. 45. 55.]


In [ ]:
a=np.array([1,2,3])

In [ ]:
a.shape

(3,)

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.array([1.1,2.1,3.1])
print(b.shape)
print(b.ndim)
print(b.dtype)

(3,)
1
float64


## 넘파이 인덱스, 슬라이싱

In [ ]:
# 넘파이 인덱싱, 슬라이싱 : 리스트 슬라이싱과 동일
score=np.array([88,72,93,94,89,78,99])
score[1:4]

array([72, 93, 94])

In [ ]:
score[::-1]

array([99, 78, 89, 94, 93, 72, 88])

In [ ]:
score[0::2]

array([88, 93, 89, 99])

## 논리적인 인덱싱

In [ ]:
# 논리적인 인덱싱
ages=np.array([18,19,25,30,28])
ages>20

array([False, False,  True,  True,  True])

In [ ]:
y=ages>20
y

array([False, False,  True,  True,  True])

In [ ]:
ages[y]

array([25, 30, 28])

In [ ]:
ages[ages>20]

array([25, 30, 28])

## 2차원 배열

In [ ]:
# 2차원 구조
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(4, 3)

In [ ]:
print(arr2.shape[0])
print(arr2.shape[1])

4
3


In [ ]:
arr2.dtype

dtype('int64')

## 2차원 리스트, 슬라이싱

In [ ]:
import numpy as np
y = [[1,2,3], [4,5,6], [7,8,9]]
y

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np_array = np.array(y)
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np_array.shape)
print(np_array.ndim)
print(np_array.dtype)

(3, 3)
2
int32


In [ ]:
np_array[1,1]

5

In [ ]:
np_array[2,0]

7

In [ ]:
np_array[2,2] = 1000
np_array

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,    8, 1000]])

In [ ]:
import numpy as np
np_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np_array[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [ ]:
np_array[0, :]

array([1, 2, 3, 4])

In [ ]:
np_array[1, 1:3]

array([6, 7])

In [ ]:
np_array[np_array>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## arange()

In [ ]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(1,6,2)

array([1, 3, 5])

## linspace()

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## reshape()

In [ ]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
yy = y.reshape(3,4)
yy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# -1을 인수로 전달하면 데이터의 개수에 맞춰서 자동으로
yyy = y.reshape(-1,4)
yyy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
y.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

## flatten()

In [ ]:
yyy.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])